// packages/html-kit/src/lib/components/Badge.svelte
<span class={ [
  'text-sm font-medium me-2 px-2 py-1 rounded-sm',
  variants[variant]
] }>
  {@render children()}
</span>

<script lang="ts">
import type { Snippet } from 'svelte';

type Variant = 'default' | 'dark' | 'red' | 'green' | 'yellow' | 'indigo' | 'purple' | 'pink';

interface Props {
  children: Snippet;
  variant: Variant;
}

let {
  children,
  variant = 'default'
}: Props = $props();

const variants: Record<Variant, string> = {
  default: 'bg-blue-100 text-blue-800',
  dark: 'bg-gray-100 text-gray-800',
  red: 'bg-red-100 text-red-800',
  green: 'bg-green-100 text-green-800',
  yellow: 'bg-yellow-100 text-yellow-800',
  indigo: 'bg-indigo-100 text-indigo-800',
  purple: 'bg-purple-100 text-purple-800',
  pink: 'bg-pink-100 text-pink-800'
};
</script>

// packages/html-report/src/components/common/Badge.vue
<template>
	<span
		:class="[variantClasses[variant]]"
		class="rounded-sm border px-2.5 py-0.5 font-medium"
	>
		<slot />
	</span>
</template>

<script setup lang="ts">
type Variants = 'primary' | 'dark' | 'red' | 'green' | 'yellow';

interface Props {
	variant?: Variants;
}

withDefaults(defineProps<Props>(), {
	variant: 'primary'
});

const variantClasses = {
	primary: 'bg-blue-100 text-blue-800 border-blue-200',
	dark: 'bg-gray-100 text-gray-800 border-gray-200',
	red: 'bg-red-100 text-red-800 border-red-200',
	green: 'bg-green-100 text-green-800 border-green-200',
	yellow: 'bg-yellow-100 text-yellow-800 border-yellow-200'
};
</script>
