// packages/html-report/src/components/Level.svelte
{#each tiles as tile, index ( children[index].path ) }
	<Tile
		tile={ tile}
		content={ children[index] }
	/>
{/each}

<script lang="ts">
import Tile from './Tile.svelte';
import { TreeMapGenerator } from '../TreeMapGenerator';
import type { Content } from '../parser';

interface Props {
	content: Content;
	width: number;
	height: number;
	xStart: number;
	yStart: number;
}

let {
	content,
	width,
	height,
	xStart,
	yStart
}: Props = $props();

const children = $derived.by(() => {
	if ( content.type === 'file' ) {
		return [];
	}

	return Object
		.values<Content>( content.contents )
		.sort( ( a, b ) => b.bytes - a.bytes );
});

const tiles = $derived.by( () => {
	if ( !children.length ) {
		return [];
	}

	const generator = new TreeMapGenerator(
		children.map( child => child.bytes ),
		width,
		height,
		xStart,
		yStart
	);

	return generator.calculate();
} );
</script>

// packages/html-report/src/components/Level.vue
<template>
	<Tile
		v-for="( tile, index ) in tiles"
		:key="children[index].path"
		:tile="tile"
		:content="children[index]"
	/>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import Tile from './Tile.vue';
import { TreeMapGenerator } from '../TreeMapGenerator';
import type { Content } from '../data';

const props = defineProps<{
	content: Content;
	width: number;
	height: number;
	xStart: number;
	yStart: number;
}>();

const children = computed<Array<Content>>(() => {
	if ( props.content.type === 'file' ) {
		return [];
	}

	return Object
		.values<Content>( props.content.contents )
		.sort( ( a, b ) => b.bytes - a.bytes );
});

const tiles = computed( () => {
	if ( !children.value.length ) {
		return [];
	}

	const generator = new TreeMapGenerator(
		children.value.map( child => child.bytes ),
		props.width,
		props.height,
		props.xStart,
		props.yStart
	);

	return generator.calculate();
} );
</script>
