// packages/html-vue/src/components/common/Tabs.vue
<template>
	<div
		class="flex items-center gap-2 w-full border-b-2 border-gray-100"
	>
		<button
			v-for="option in props.options"
			:key="option.value"
			:disabled="option.disabled"
			:class="[
				'flex items-center justify-center gap-2 py-2 px-6 -mb-0.5 text-sm rounded-t-lg border-b-2 border-transparent text-gray-500 outline-hidden cursor-pointer',
				model === option.value && 'border-b-gray-500 text-gray-900 bg-gray-50',
				'transition-colors duration-150',
				'disabled:opacity-50 disabled:cursor-not-allowed'
			]"
			@click="() => model = option.value"
		>
			{{ option.label }}
		</button>
	</div>
</template>

<script setup lang="ts">

interface Props {
	options: Array<{
		label: string;
		value: string;
		disabled?: boolean;
	}>;
}

const model = defineModel<string>();
const props = defineProps<Props>();
</script>

// packages/html-kit/src/lib/components/Tabs/Tabs.svelte
<div class="inline-flex h-12 items-center justify-center gap-1 rounded-lg bg-gray-100 p-2 text-gray-600">
  {#each values as { value, label, active }}
    <button
      class={ [
        'inline-flex items-center justify-center whitespace-nowrap rounded-md px-3 py-1',
        // Value is selected
        value === current
          ? 'bg-gray-700 shadow text-gray-100'
          // Value is available
          : active === false
          ? 'cursor-not-allowed text-gray-400'
          // Value is available, but not selected
          : 'hover:bg-gray-200',
      ] }
      onclick={() => { if ( active !== false ) current = value } }
    >
      { label }
    </button>
  {/each}
</div>

<script lang="ts">
import type { Tab } from '$lib/types';

interface Props {
  values: Array<Tab>;
  current: string;
}

let { values, current = $bindable() }: Props = $props();
</script>
