// packages/html-report/src/components/common/Tabs.vue
<template>
	<div>
		<!-- Tabs list -->
		<div
			role="tablist"
			class="flex items-center gap-2 p-1 rounded-lg border border-gray-200 bg-gray-50 overflow-x-auto overflow-y-hidden"
		>
			<button
				v-for="option in props.options"
				:key="option.value"
				:disabled="option.disabled"
				:class="[
					'flex items-center justify-center gap-2 py-2 px-6 text-sm rounded-md border text-gray-500 outline-hidden cursor-pointer select-none focus:border-gray-300 hover:border-gray-300',
					model === option.value ? 'border-gray-300 text-gray-700 bg-white shadow-xs' : 'border-transparent',
					'transition-colors duration-150',
					'disabled:opacity-50 disabled:cursor-not-allowed'
				]"
				role="tab"
				@click="() => model = option.value"
			>
				{{ option.label }}
			</button>
		</div>

		<!-- Tab content -->
		 <div
      role="tabpanel"
      class="pt-4"
    >
      <slot :name="model" />
    </div>
	</div>
</template>

<script setup lang="ts">
interface Props {
	options: Array<{
		label: string;
		value: string;
		disabled?: boolean;
	}>;
}

const model = defineModel<string>();
const props = defineProps<Props>();
</script>

// packages/html-kit/src/lib/components/Tabs/Tabs.svelte
<div class="inline-flex h-12 items-center justify-center gap-1 rounded-lg bg-gray-100 p-2 text-gray-600">
  {#each values as { value, label, active }}
    <button
      class={ [
        'inline-flex items-center justify-center whitespace-nowrap rounded-md px-3 py-1',
        // Value is selected
        value === current
          ? 'bg-gray-700 shadow text-gray-100'
          // Value is available
          : active === false
          ? 'cursor-not-allowed text-gray-400'
          // Value is available, but not selected
          : 'hover:bg-gray-200',
      ] }
      onclick={() => { if ( active !== false ) current = value } }
    >
      { label }
    </button>
  {/each}
</div>

<script lang="ts">
import type { Tab } from '$lib/types';

interface Props {
  values: Array<Tab>;
  current: string;
}

let { values, current = $bindable() }: Props = $props();
</script>
