// packages/html-report/src/components/layout/Breadcrumbs.vue
<template>
	<nav
		class="-mx-2 w-full text-gray-700"
		aria-label="Breadcrumb"
	>
		<ol class="inline-flex w-full items-center gap-1">
			<template
				v-for="(part, index) in parts"
				:key="index"
			>
				<li v-if="index !== 0">
					<IconChevronLeft
						:size="16"
						class="rotate-180"
					/>
				</li>

				<li v-if="index !== parts.length - 1">
					<a
						:href="part.url"
						class="rounded-lg px-2 py-1 text-sm font-medium text-gray-700 underline-offset-2 outline-hidden hover:underline focus:border-gray-500 focus:ring focus:ring-gray-500"
					>
						{{ part.name }}
					</a>
				</li>

				<li
					v-else
					aria-current="page"
					class="truncate px-2 py-1 text-gray-500"
				>
					{{ part.name }}
				</li>
			</template>
		</ol>
	</nav>
</template>

<script setup lang="ts">
import { router } from '@/router.js';
import IconChevronLeft from '@icon/ChevronLeft.vue';
import { computed } from 'vue';

const parts = computed(() => {
	const parts = [{ name: 'Home', url: router.getUrl('') }];

	const route = router.path.split('/')[0];
	const itemId = router.query.item;

	if (route) {
		parts.push({ name: capitalize(route), url: router.getUrl(route) });
	}

	if (route && itemId) {
		parts.push({ name: itemId, url: router.getUrl(route, { id: itemId }) });
	}

	return parts;
});

function capitalize(title: string): string {
	return title.charAt(0).toUpperCase() + title.slice(1);
}
</script>

// packages/html-kit/src/lib/components/Header/Breadcrumbs.svelte
<nav>
  <ol class="flex flex-wrap items-center gap-1.5 break-words text-sm">
    {#each segments as [ name, href ], i }
      {#if i + 1 === segments.length}
        <li class="inline-flex gap-1.5">{ name }</li>
      {:else}
        <li class="inline-flex gap-1.5 text-gray-500 hover:text-gray-800">
          <a href={ href }>{ name }</a>
        </li>

        <li><ChevronRight size="16" class="text-gray-500" /></li>
      {/if}
    {/each}
  </ol>
</nav>

<script lang="ts">
import { page } from '$app/state';
import { ChevronRight } from 'lucide-svelte';

const segments = $derived.by( () => {
  const parts: Array<[ string, string ]> = [];
  const [ , route, ...path ] = page.url.hash.split( '/' );

  parts.push( [ 'Home', '#/' ] );
  route && parts.push( [ capitalize( route ), '#/' + route ] );
  path.length && parts.push( [ path.join( '/' ), page.url.hash ] );

  return parts;
} );

function capitalize( text: string ): string {
  return text.charAt( 0 ).toUpperCase() + text.slice( 1 );
}
</script>
