// packages/html-kit/src/routes/inputs/+page.svelte
<div class="flex mb-4 items-center h-12">
  <div class="grow flex gap-4">
    <p class="col-span-12 text-2xl font-bold text-gray-900">Inputs</p>
  </div>
</div>

<div class="relative overflow-x-auto">
  <table class="w-full text-sm text-left table-auto text-gray-500">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50">
      <tr>
        <th class="px-6 py-3">Path</th>
        <th class="px-6 py-3">Bytes</th>
        <th class="px-6 py-3">Format</th>
        <th class="px-6 py-3">Source</th>
        <th class="px-6 py-3">Used in</th>
        <th class="px-6 py-3">Imports</th>
        <th class="px-6 py-3">Imported by</th>
      </tr>
    </thead>
    <tbody class="align-top">
      {#each mappedInputs as input}
        <tr class="bg-white border-b border-gray-200">
          <th class="px-6 py-4 font-medium text-gray-900">
            <span data-hover={ input.path }>{ input.name }</span>
          </th>
          <td class="px-6 py-4 whitespace-nowrap text-gray-900">{ input.formattedBytes }</td>
          <td class="px-6 py-4 whitespace-nowrap">
            <Badge variant={ formatVariant[ input.format ] }>{ input.format }</Badge>
          </td>
          <td class="px-6 py-4 whitespace-nowrap">
            <Badge variant={ sourceVariant[ input.source ] }>{ input.source }</Badge>
          </td>
          <td class="px-6 py-4 whitespace-nowrap">
            <ul>
              {#each input.usedIn as path}
                <li>
                  <a
                    href={ '#/assets/' + path }
                    class="text-blue-500 hover:underline underline-offset-4"
                  >
                    { path }
                  </a>
                </li>
              {/each}
            </ul>
          </td>
          <td class="px-6 py-4">
            <ul>
              {#each input.imports as path}
                <li>
                  <span data-hover={ path }>{ path }</span>
                </li>
              {/each}
            </ul>
          </td>
          <td class="px-6 py-4">
            <ul>
              {#each input.importedBy as path}
                <li>
                  <span data-hover={ path }>{ path }</span>
                </li>
              {/each}
            </ul>
          </td>
        </tr>
        {/each}
    </tbody>
  </table>
</div>

<script lang="ts">
import { store } from '$lib/store.svelte.js';
import { formatSize } from '$lib/helpers/format';
import Badge from '$lib/components/Badge.svelte';

const modules = 'node_modules';

const mappedInputs = Object
  .entries( store.report.inputs )
  .map( ( [ path, input ] ) => ({
    path,
    ...input,
    name: removeNodeModulesPath( path ),
    formattedBytes: formatSize( input.bytes ),
    usedIn: getUsedIn( path ),
    imports: input.imports.map( removeNodeModulesPath ),
    importedBy: getImportedBy( path ),
    source: path.includes( modules ) ? 'external' : 'internal'
  }) )
  .toSorted( ( a, b ) => a.path.localeCompare( b.path ) );

const sourceVariant: Record<any, any> = {
  internal: 'dark',
  external: 'default'
};

const formatVariant: Record<any, any> = {
  esm: 'yellow',
  cjs: 'default',
  unknown: 'dark'
};

function removeNodeModulesPath( path: string ): string {
  const index = path.lastIndexOf( modules );

  return index !== -1
    ? path.slice( index + modules.length + 1 )
    : path;
}

function getUsedIn( path: string ): Array<string> {
  return Object.entries( store.report.outputs )
    .filter( ( [ , output ] ) => output.inputs[ path ] )
    .map( ( [ path ] ) => path );
}

function getImportedBy( path: string ): Array<string> {
  return Object.entries( store.report.inputs )
    .filter( ( [ , input ] ) => input.imports.includes( path ) )
    .map( ( [ path ] ) => removeNodeModulesPath( path ) );  
}
</script>

// packages/html-vue/src/pages/Inputs/Index.vue
<template>
	<div class="max-w-7xl flex flex-col">
		<h2 class="text-2xl font-bold">Input files</h2>

		<p class="text-gray-500 mt-4">
			List of input (source) files used in the generated bundles. This includes all internal files in your project as well as external files from <code class="text-xs py-0.5 px-1 bg-gray-100 rounded">node_modules</code>.
		</p>

		<hr class="mt-4 mb-6 border-gray-100">

		<div class="flex gap-2 mb-4">
			<div class="relative flex">
				<div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
					<IconSearch :size="16" class="text-gray-500" />
				</div>

				<input
					v-model="search"
					type="text"
					class="py-1.25 ps-10 w-80 text-sm text-gray-900 border border-gray-300 bg-white rounded-lg outline-hidden shadow-xs placeholder:text-gray-500 focus:ring focus:ring-gray-500 focus:border-gray-500"
					placeholder="Filter input files"
				>
			</div>

			<Dropdown
				v-model="formats"
				:options="FORMAT_OPTIONS"
				title="Format"
			>
				<template #icon>
					<IconFunnel :size="16" />
				</template>
			</Dropdown>

			<Dropdown
				v-model="sources"
				:options="SOURCE_OPTIONS"
				title="Source"
			>
				<template #icon>
					<IconFunnel :size="16" />
				</template>
			</Dropdown>
		</div>

		<DataTable
			v-model="active"
			:columns="COLUMNS"
			:data="paginatedData"
		>
			<template #row="{ item }">
				<td class="p-3 font-normal text-center whitespace-nowrap">
					<BaseButton
						:link="true"
						:href="router.getUrl( 'inputs/details', { item: item.path } )"
						class="flex rounded border border-gray-300 p-2"
					>
						<IconSearch :size="16" class="text-gray-500" />	
					</BaseButton>
				</td>
	
				<td class="p-3 font-normal text-gray-900">
					<p
						:title="item.path"
						class="truncate"
					>
						{{ item.name }}
					</p>
				</td>

				<td class="p-3 font-normal">
					<!-- <p
						v-for="output in item.outputs"
						:key="output"
						:title="output"
						class="truncate"
					>
						{{ output }}
					</p> -->
				</td>

				<td class="p-3 font-normal text-center whitespace-nowrap">
					<Badge v-if="item.format === 'esm'" variant="yellow">esm</Badge>
					<Badge v-else-if="item.format === 'cjs'" variant="primary">cjs</Badge>
					<Badge v-else variant="dark">unknown</Badge>
				</td>

				<td class="p-3 font-normal text-center whitespace-nowrap">
					<Badge v-if="item.source ==='internal'" variant="dark">internal</Badge>
					<Badge v-else variant="primary">external</Badge>
				</td>
			</template>
		</DataTable>

		<Pagination
			v-model="currentPage"
			:count="filteredData.length"
			:items-per-page="ITEMS_PER_PAGE"
		/>
	</div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { router } from '@/router.js'
import { report } from '@/report.js';
import { formatPath } from '@/format.js';
import DataTable, { type Column } from '@components/common/DataTable.vue';
import Dropdown from '@components/common/Dropdown.vue';
import BaseButton from '@/components/common/Button.vue';
import Pagination from '@components/common/Pagination.vue';
import Badge from '@components/common/Badge.vue';
import IconSearch from '@components/icon/Search.vue';
import IconFunnel from '@components/icon/Funnel.vue';

const ITEMS_PER_PAGE = 12;

const FORMAT_OPTIONS = [
	{ label: 'ESM', subLabel: 'ES Module', value: 'esm' },
	{ label: 'CJS', subLabel: 'CommonJS', value: 'cjs' },
	{ label: 'Unknown', value: 'unknown' },
	{ label: 'Other', value: 'other' }
];

const SOURCE_OPTIONS = [
	{ label: 'Internal', value: 'internal' },
	{ label: 'External', value: 'external' },
];

const COLUMNS: Array<Column> = [
	{
		name: '',
		align: 'center',
		width: '58px'
	},
	{
		name: 'Path',
		align: 'left',
		width: '66.6%'
	},
	{
		name: 'Used in',
		align: 'left',
		width: '33.3%'
	},
	{
		name: 'Format',
		align: 'center',
		width: '106px'
	},
	{
		name: 'Source',
		align: 'center',
		width: '106px'
	}
];

const inputs = Object.entries( report.inputs );

const data = ref(
	inputs.map( ( [ path, input ] ) => ( {
		id: path,
		path,
		name: formatPath( path ),
		format: input.format,
		source: path.includes( 'node_modules' ) ? 'external' : 'internal'
	} ) )
);

const search = computed( router.computedQuery( 'search', '' ) );
const formats = computed( router.computedQuery( 'formats', FORMAT_OPTIONS.map( o => o.value ) ) );
const sources = computed( router.computedQuery( 'sources', SOURCE_OPTIONS.map( o => o.value ) ) );
const currentPage = computed( router.computedQuery( 'page', 1 ) );
const active = computed( router.computedQuery( 'active', '' ) );

const filteredData = computed( () => {
	const lowercaseSearch = search.value.toLowerCase();

	return data.value.filter( item => {
		return formats.value.includes( item.format )
			&& sources.value.includes( item.source )
			&& item.path.toLowerCase().includes( lowercaseSearch );
	} );
} );

const paginatedData = computed( () => {
	const start = ( currentPage.value - 1 ) * ITEMS_PER_PAGE;
	const end = start + ITEMS_PER_PAGE;

	return filteredData.value.slice( start, end );
} );

watch( [ search, formats, sources, currentPage ], () => {
	active.value = '';
} );

watch( [ search, formats, sources ], () => {
	currentPage.value = 1;
} );
</script>
