// packages/html-report/src/components/Tooltip.svelte
<svelte:body
	bind:clientWidth={ bodyWidth }
	bind:clientHeight={ bodyHeight }
	onmouseover={ onMouseMove }
	onmousemove={ onMouseMove }
	onmouseleave={ () => content = '' }
/>

<div
	bind:clientWidth={ width }
	bind:clientHeight={ height }
	role="tooltip"
	class="fixed z-10 px-2 py-1 bg-gray-800 text-gray-100 rounded-md whitespace-nowrap pointer-events-none will-change-transform"
	class:invisible={ !content }
	style="transform: translate( var(--x), var(--y) )"
	style:--x={ x }
	style:--y={ y }
>
	{ content }
</div>

<script lang="ts">
const margin = 12;

let width = $state<number>( 0 );
let height = $state<number>( 0 );
let bodyWidth = $state<number>( 0 );
let bodyHeight = $state<number>( 0 );
let mouseX = $state<number>( 0 );
let mouseY = $state<number>( 0 );
let content = $state<string>( '' );
let x = $state<string>( '0px' );
let y = $state<string>( '0px' );

$effect(() => {
	if ( !content ) return;

	// Update tooltip position in one batch
	x = ( mouseX + width + margin > bodyWidth ? mouseX - width - margin : mouseX + margin ) + 'px';
	y = ( mouseY + height + margin > bodyHeight ? mouseY - height : mouseY + margin ) + 'px';
});

function onMouseMove( { target, clientX, clientY }: MouseEvent ) {
	content = target instanceof Element && target.getAttribute( 'data-hover' ) || '';
	mouseX = clientX;
	mouseY = clientY;
}
</script>

// packages/html-report/src/components/layout/Tooltip.vue
<template>
  <div
    ref="tooltipRef"
		:class="{ invisible: !content }"
    :style="{ '--x': x, '--y': y }"
    role="tooltip"
    class="fixed z-10 max-w-[400px] px-2 py-1 bg-gray-800 text-gray-100 rounded-md break-words pointer-events-none"
  >
    <span>{{ content }}</span>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue';

const margin = 12;

// reactive dimensions
const bodyWidth = ref(0);
const bodyHeight = ref(0);
const width = ref(0);
const height = ref(0);

// tooltip state
const content = ref( '' );
const x = ref( '0px' );
const y = ref( '0px' );

// tooltip DOM ref
const tooltipRef = ref<HTMLElement | null>(null);

function resetContent() {
  content.value = '';
}

function onMouseMove(event: MouseEvent) {
  const target = event.target as Element;
  content.value = target.getAttribute( 'data-hover' ) || '';
  if (!content.value) return;

  const { clientX, clientY } = event;
  const calcX =
    clientX + width.value + margin > bodyWidth.value
      ? clientX - width.value - margin
      : clientX + margin;
  const calcY =
    clientY + height.value + margin > bodyHeight.value
      ? clientY - height.value
      : clientY + margin;

  x.value = `${calcX}px`;
  y.value = `${calcY}px`;
}

let resizeObserver: ResizeObserver;

onMounted(() => {
  resizeObserver = new ResizeObserver(entries => {
    for (const entry of entries) {
      const { width: w, height: h } = entry.contentRect;
      if (entry.target === document.body) {
        bodyWidth.value = w;
        bodyHeight.value = h;
      } else if (entry.target === tooltipRef.value) {
        width.value = w;
        height.value = h;
      }
    }
  });

  // start observing both targets
  resizeObserver.observe(document.body);
  if (tooltipRef.value) {
    resizeObserver.observe(tooltipRef.value);
  }

  document.body.addEventListener('mousemove', onMouseMove);
  document.body.addEventListener('mouseover', onMouseMove);
  document.body.addEventListener('mouseleave', resetContent);
});

onBeforeUnmount(() => {
  resizeObserver.disconnect();
  document.body.removeEventListener('mousemove', onMouseMove);
  document.body.removeEventListener('mouseover', onMouseMove);
  document.body.removeEventListener('mouseleave', resetContent);
});
</script>

<style scoped>
div[role="tooltip"] {
  transform: translate(var(--x), var(--y));
  will-change: transform, contents;
}
</style>
