// packages/html-vue/src/components/treemap/Treemap.vue
<template>
  <svg
    :width="width"
    :height="height"
    xmlns="http://www.w3.org/2000/svg"
    role="img"
  >
    <!-- Subtract 1 and start at 0.5 to prevent stroke clipping at viewport edges -->
    <Level
      :content="content"
      :totalBytes="totalBytes"
      :width="innerWidth"
      :height="innerHeight"
      :xStart="0.5"
      :yStart="0.5"
    >
      <slot />
    </Level>
  </svg>
</template>

<script lang="ts" setup>
import { computed } from 'vue';
import Level from './Level.vue';
import type { Folder } from '@/FileSystemTrie';

interface Props {
  width: number;
  height: number;
  content: Folder;
}

const props = defineProps<Props>();

const totalBytes = computed( () => props.content.uncompressed );
const innerWidth = computed( () => props.width - 1 );
const innerHeight = computed( () => props.height - 1 );
</script>

// packages/html-kit/src/lib/components/Treemap/Treemap.svelte
<!-- Re-render the entire SVG when path, width, or height change -->
{#key [ content.path, width, height ]}
	<svg
		{ width }
		{ height }
		xmlns="http://www.w3.org/2000/svg"
		role="img"
	>
		<!-- Substract 1 and start at 0.5 to prevent stroke clipping at viewport edges -->
		<Level
			{ content }
			totalBytes={ content[ store.compression ] }
			width={ width - 1 }
			height={ height - 1 }
			xStart={ 0.5 }
			yStart={ 0.5 }
		/>
	</svg>
{/key}

<script lang="ts">
import Level from './Level.svelte';
import { store } from '$lib/store.svelte.js';
import type { Folder } from '$lib/helpers/FileSystemTrie';

interface Props {
	width: number;
	height: number;
	content: Folder;
}

let {
	width,
	height,
	content
}: Props = $props();
</script>
