// packages/html-kit/src/routes/dependencies/+page.svelte
<div class="flex mb-4 items-center h-12">
  <div class="grow flex gap-4">
    <p class="col-span-12 text-2xl font-bold text-gray-900">Dependencies</p>
  </div>
</div>

<div class="relative overflow-x-auto">
  <table class="w-full text-sm text-left table-auto text-gray-500">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50">
      <tr>
        <th class="px-6 py-3">Name</th>
        <th class="px-6 py-3">Paths</th>
        <th class="px-6 py-3">Used by</th>
      </tr>
    </thead>
    <tbody class="align-top">
      {#each mappedDependencies as dependency}
        <tr class="bg-white border-b border-gray-200">
          <th class="px-6 py-4 whitespace-nowrap font-medium text-gray-900">{ dependency.name }</th>
          <td class="px-6 py-4">
            <ul>
              {#each dependency.paths as path}
                <li>{ path }</li>
              {/each}
            </ul>
          </td>
          <td class="px-6 py-4 text-gray-900 whitespace-nowrap">
            <ul>
              {#each dependency.usedIn as path}
                <li>
                  <a
                    href={ '#/assets/' + path }
                    class="text-blue-500 hover:underline underline-offset-4"
                  >
                    { path }
                  </a>
                </li>
              {/each}
            </ul>
          </td>
        </tr>
      {/each}
    </tbody>
  </table>
</div>

<script lang="ts">
import { store } from '$lib/store.svelte.js';

const mappedDependencies = Object
  .entries( store.report.dependencies )
  .map( ( [ name, paths ] ) => ({
    name,
    paths,
    usedIn: getUsedIn( name )
  }) )
  .toSorted( ( a, b ) => a.name.localeCompare( b.name ) );

function getUsedIn( dependencyName: string ) {
  return Object.entries( store.report.outputs )
    .filter( ( [ , output ] ) => {
      return Object.keys( output.inputs ).some( input => input.includes( dependencyName ) )
    } )
    .map( ( [ name ] ) => name );
}
</script>

// packages/html-vue/src/components/sections/Assets/Dependencies.vue
<template>
	<Collapsible
		v-if="dependencies.length"
		v-model="show"
	>
		<template #title>Dependencies</template>
		<template #description>List of dependencies used in the asset</template>

		<div class="rounded-lg border border-gray-200 shadow-xs">
			<table class="table-fixed w-full text-sm text-left">
				<tbody class="text-gray-700">
					<tr
						v-for="( dependency, index ) in dependencies"
						:key="dependency"
						class="[&:not(:first-child)]:border-t border-gray-100"
					>
						<td class="p-3 font-normal">
							<span class="select-none mr-2">{{ index + 1 }}.</span>
							<a
								:href="router.getUrl( 'dependencies', { search: dependency, active: dependency } )"
								class="px-2 py-1 text-sm font-medium underline-offset-2 rounded-lg outline-hidden focus:ring focus:ring-gray-500 focus:border-gray-500 hover:underline"
							>
								{{ dependency }}
							</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</Collapsible>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { router } from '@/router.js';
import { report } from '@/report.js';
import Collapsible from '@/components/common/Collapsible.vue';

interface Props {
	name: string;
	inputs: string[];
}

const props = defineProps<Props>();
const show = computed( router.computedQuery( 'dependencies', false ) );

const dependencies = computed( () => {
	return report.dependencies
		.filter( dependency => dependency.paths.some( path => props.inputs.some( input => input.includes( path ) ) ) )
		.map( dependency => dependency.name )
		.toSorted();
} )
</script>
