// packages/html-report/src/components/Treemap/Level.svelte
{#each tiles as tile, index (tile)}
	<Tile
		{ tile }
		content={ children[index] }
		{ totalBytes }
	/>
{/each}

<script lang="ts">
import Tile from './Tile.svelte';
import { generateTreeMap } from '../../treemap';
import { compression } from '../../stores/index.svelte.js';
import type { Content } from '../../FileSystemTrie';

interface Props {
	content: Content | Array<Content>;
	totalBytes: number;
	width: number;
	height: number;
	xStart: number;
	yStart: number;
}

let {
	content,
	totalBytes,
	width,
	height,
	xStart,
	yStart
}: Props = $props();

const children = $derived.by(() => {
	if ( !Array.isArray( content ) ) {
		return [ content ];
	}

	return Object.values<Content>( content );
});

const tiles = $derived(
	generateTreeMap( children.map( child => child[ compression.type ] ), width, height, xStart, yStart )
);
</script>

// packages/html-vue/src/components/treemap/Level.vue
<template>
  <Tile
    v-for="(tile, index) in tiles"
    :totalBytes
    :tile
    :content="children[ index ]"
  />
</template>

<script lang="ts" setup>
import { computed } from 'vue';
import Tile from './Tile.vue';
import { generateTreeMap } from '@/treemap.js';
import type { Content } from '@/FileSystemTrie'

interface Props {
  content: Content | Content[]
  totalBytes: number
  width: number
  height: number
  xStart: number
  yStart: number
}

const props = defineProps<Props>()

const children = computed<Content[]>( () => Array.isArray( props.content ) ? props.content: [ props.content ] );
const tiles = computed(() => generateTreeMap(
  children.value.map( child => child.uncompressed) ,
  props.width,
  props.height,
  props.xStart,
  props.yStart
) );
</script>
